"""Initial migration

Revision ID: 3412cb7b91bb
Revises: 
Create Date: 2026-06-11 11:26:19.752380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3412cb7b91bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conjunctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sat1_norad_id', sa.String(length=10), nullable=False),
    sa.Column('sat2_norad_id', sa.String(length=10), nullable=False),
    sa.Column('approach_time', sa.DateTime(), nullable=False),
    sa.Column('miss_distance_km', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conjunctions_id'), 'conjunctions', ['id'], unique=False)
    op.create_index(op.f('ix_conjunctions_sat1_norad_id'), 'conjunctions', ['sat1_norad_id'], unique=False)
    op.create_index(op.f('ix_conjunctions_sat2_norad_id'), 'conjunctions', ['sat2_norad_id'], unique=False)
    op.create_table('satellites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('norad_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=20), nullable=False),
    sa.Column('tle_line1', sa.String(length=80), nullable=False),
    sa.Column('tle_line2', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satellites_id'), 'satellites', ['id'], unique=False)
    op.create_index(op.f('ix_satellites_norad_id'), 'satellites', ['norad_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_satellites_norad_id'), table_name='satellites')
    op.drop_index(op.f('ix_satellites_id'), table_name='satellites')
    op.drop_table('satellites')
    op.drop_index(op.f('ix_conjunctions_sat2_norad_id'), table_name='conjunctions')
    op.drop_index(op.f('ix_conjunctions_sat1_norad_id'), table_name='conjunctions')
    op.drop_index(op.f('ix_conjunctions_id'), table_name='conjunctions')
    op.drop_table('conjunctions')
    # ### end Alembic commands ###
